In [87]:
import os
import keras
#from keras.models import Sequential
#from keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array
#from keras.layers import Conv2D ,MaxPooling2D,AveragePooling2D ,Flatten , Dense,Dropout,BatchNormalization
from PIL import Image
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('dark_background')
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
import pickle
import cv2
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [68]:
data = []
category = []

In [69]:
from google.colab import drive
drive.mount('/content/drive')

path = '/content/drive/My Drive/brain_tumor_dataset'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [70]:
for filename in os.scandir("/content/drive/My Drive/brain_tumor_dataset/no"):
    if filename.is_file():
        #print(filename.path)
        img = Image.open(filename.path)
        img = img.resize(size=(32,32))
        img = img.convert('L')
        data.append(np.array(img).flatten())
        category.append(0)
        del img

In [72]:
for filename in os.scandir("/content/drive/My Drive/brain_tumor_dataset/yes"):
    if filename.is_file():
        #print(filename.path)
        img = Image.open(filename.path)
        img = img.resize(size=(32,32))
        img = img.convert('L')
        data.append(np.array(img).flatten())
        category.append(1)
        del img

In [73]:
x,y = np.array(data),category

In [74]:
x.shape

(408, 1024)

In [75]:
len(y)

408

In [76]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.1,random_state=1)

In [114]:
## Normalization
# scaler = StandardScaler()
# X_train = scaler.fit_transform(x_train)
# X_test = scaler.transform(x_test)

**Logistic Regression**

In [90]:
from sklearn.linear_model import LogisticRegression
lg = LogisticRegression()

In [115]:
lg.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [116]:
lg.score(x_train,y_train)

1.0

In [117]:
lg.score(x_test,y_test)

0.926829268292683

**Support Vector Machine**


In [97]:
from sklearn.svm import SVC
svm_model = SVC(kernel='linear',C = 0.1,random_state=0)

In [118]:
svm_model.fit(x_train,y_train)

SVC(C=0.1, kernel='linear', random_state=0)

In [119]:
svm_model.score(x_train,y_train)

1.0

In [120]:
svm_model.score(x_test,y_test)

0.926829268292683

In [121]:
y_pred_train_svm = svm_model.predict(x_train)
train_accuracy = accuracy_score(y_train, y_pred_train_svm)
print(f'Train Accuracy: {train_accuracy}')

Train Accuracy: 1.0


In [122]:
y_pred = svm_model.predict(x_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.926829268292683
Confusion Matrix:
 [[ 9  3]
 [ 0 29]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.75      0.86        12
           1       0.91      1.00      0.95        29

    accuracy                           0.93        41
   macro avg       0.95      0.88      0.90        41
weighted avg       0.93      0.93      0.92        41



In [86]:
# def load_data(data_path):
#     data = load_files(data_path, shuffle=True)
#     file_paths = np.array(data['filenames'])
#     labels = np.array(data['target'])
#     return file_paths, labels

In [87]:
# file_paths, labels = load_data(path)
# labels

array([1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1])

In [88]:
# file_paths

array(['/content/drive/My Drive/brain_tumor_dataset/yes/Y193.JPG',
       '/content/drive/My Drive/brain_tumor_dataset/no/no 7.jpeg',
       '/content/drive/My Drive/brain_tumor_dataset/yes/Y245.jpg',
       '/content/drive/My Drive/brain_tumor_dataset/yes/Y101.jpg',
       '/content/drive/My Drive/brain_tumor_dataset/yes/Y183.jpg',
       '/content/drive/My Drive/brain_tumor_dataset/yes/Y38.jpg',
       '/content/drive/My Drive/brain_tumor_dataset/yes/Y12.jpg',
       '/content/drive/My Drive/brain_tumor_dataset/yes/Y7.jpg',
       '/content/drive/My Drive/brain_tumor_dataset/no/No11.jpg',
       '/content/drive/My Drive/brain_tumor_dataset/yes/Y161.JPG',
       '/content/drive/My Drive/brain_tumor_dataset/yes/Y182.JPG',
       '/content/drive/My Drive/brain_tumor_dataset/yes/Y75.JPG',
       '/content/drive/My Drive/brain_tumor_dataset/yes/Y109.JPG',
       '/content/drive/My Drive/brain_tumor_dataset/yes/Y28.jpg',
       '/content/drive/My Drive/brain_tumor_dataset/yes/Y186.jpg',
  

In [89]:
# classes = ds.class_names

# plt.figure (figsize = (10,10))

# for image_batch, label_batch in ds.take(1):
#     for i in range(12):
#         axes = plt.subplot(4,3,i+1)
#         plt.imshow (image_batch[i].numpy().astype('uint8'))
#         plt.title (classes[label_batch[i]])
#         plt.axis('off')

In [90]:

# def preprocess_images(file_paths):
#     images = []
#     for file_path in file_paths:
#         image = cv2.imread(file_path)
#         image = cv2.resize(image, (128, 128))  # Resize to 128x128
#         image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)  # Convert to grayscale
#         images.append(image.flatten())  # Flatten the image
#     print(images)
#     return np.array(images)

In [91]:
# X = preprocess_images(file_paths)
# y = labels

[array([ 6,  6,  6, ..., 10, 10, 10], dtype=uint8), array([10, 10, 10, ..., 10, 10, 10], dtype=uint8), array([0, 0, 0, ..., 0, 0, 0], dtype=uint8), array([128,  58,  57, ...,  56,  56, 127], dtype=uint8), array([59, 20, 21, ..., 20, 20, 59], dtype=uint8), array([1, 1, 1, ..., 0, 1, 1], dtype=uint8), array([1, 1, 1, ..., 6, 6, 7], dtype=uint8), array([0, 0, 0, ..., 0, 0, 0], dtype=uint8), array([10, 10, 10, ..., 10, 10, 10], dtype=uint8), array([10,  8,  8, ...,  5,  1,  0], dtype=uint8), array([88, 88, 88, ...,  6,  6,  6], dtype=uint8), array([53, 13,  3, ...,  5,  7,  6], dtype=uint8), array([254, 255, 252, ..., 254, 254, 255], dtype=uint8), array([0, 0, 0, ..., 0, 0, 0], dtype=uint8), array([0, 0, 0, ..., 0, 0, 0], dtype=uint8), array([12, 12, 12, ..., 12, 12, 12], dtype=uint8), array([1, 0, 1, ..., 1, 1, 1], dtype=uint8), array([ 1,  1,  1, ..., 20, 20, 20], dtype=uint8), array([113,   7,   7, ...,   7,  42, 253], dtype=uint8), array([16, 16, 16, ..., 16, 16, 16], dtype=uint8), arr

In [92]:
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [93]:
## Normalization
# scaler = StandardScaler()
# X_train = scaler.fit_transform(X_train)
# X_test = scaler.transform(X_test)

In [94]:
# X_train

array([[ 0.13349424,  0.29853354,  0.285087  , ...,  0.20769255,
         0.19612983,  0.06470713],
       [-0.37392743, -0.33030842, -0.28993685, ..., -0.29981425,
        -0.36108852, -0.41525027],
       [-0.35580522, -0.28694001, -0.28993685, ..., -0.3186108 ,
        -0.32394063, -0.36725453],
       ...,
       [ 1.31143741,  0.32021775,  0.54065315, ...,  1.07233377,
         1.06910524,  1.52057789],
       [-0.41017183, -0.35199262, -0.35382839, ..., -0.35620389,
        -0.36108852, -0.39925169],
       [-0.31956082, -0.15683477, -0.18345095, ..., -0.22462806,
        -0.23107091, -0.30326021]])

In [95]:
# ## defining the model
# svm_model = SVC(kernel='rbf', C=1, gamma='scale')
# svm_model.fit(X_train, y_train)

SVC(C=1)

In [96]:
# y_pred_train_svm = svm_model.predict(X_train)
# train_accuracy = accuracy_score(y_train, y_pred_train_svm)
# print(f'Train Accuracy: {train_accuracy}')

Train Accuracy: 0.9554455445544554


In [97]:
## testing
# y_pred = svm_model.predict(X_test)

In [98]:
# print("Accuracy:", accuracy_score(y_test, y_pred))
# print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
# print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.8823529411764706
Confusion Matrix:
 [[11  2]
 [ 4 34]]
Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.85      0.79        13
           1       0.94      0.89      0.92        38

    accuracy                           0.88        51
   macro avg       0.84      0.87      0.85        51
weighted avg       0.89      0.88      0.88        51



In [129]:
with open('brain_tumor1_SVM.pkl', 'wb') as file:
    pickle.dump(svm_model, file)

In [124]:
def preprocess_image(file_path):
    image = cv2.imread(file_path)
    if image is None:
        raise ValueError(f"Could not read the image from path: {file_path}")
    image = cv2.resize(image, (32, 32))  # Resize to 128x128
    image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)  # Convert to grayscale
    return image.flatten()

In [130]:
uploaded_image_path = '/content/11 no.jpg'
uploaded_image = preprocess_image(uploaded_image_path)

In [128]:
prediction = svm_model.predict(np.expand_dims(uploaded_image, axis=0))
print(prediction)
# Interpret the prediction
if prediction[0] == 0:
    print("Predicted: No Brain Tumor")
else:
    print("Predicted: Brain Tumor Detected")

[0]
Predicted: No Brain Tumor
